### ISSUE TITLE
[feature request] support for custom domain

### ISSUE THREAD

**Issue by acognigni-evotecnia** [cmbuckley/setcookie.net#1]
Hi. I've been using your site for a few days and it's great. 

A site I'm working on had issues and the domain the cookies was sending was basically ".b.setcookie.net". i was trying to set a cookie that applied to all the b subdomains but not "a" and not the root. 

looking at the request the site sends when setting a cookie i can seee "dom=sub". while this works, i'd like the ability to send custom domains so that you don't have to add an UI element and backend mapping for each possible option

I can try to contribute, but no prromises. while we are at it. can you specify a licence?

Thanks

**Comment by cmbuckley-nhs** [comment]
Hi, that's a great request to add an intermediate option and I'll try get around to it.

In terms of your example, from https://a.b.setcookie.net you want an option to set a cookie on `domain=b.setcookie.net`, which makes sense.

I've added an MIT licence now if you're able to contribute 😄

**Comment by cmbuckley** [comment]
Hi, that's a great request to add an intermediate option!

In terms of your example, from https://a.b.setcookie.net you want an option to set a cookie on `domain=b.setcookie.net`, which makes sense.

It felt like an interesting problem to solve so I've added that in now. I've also added an MIT licence if you'd like contribute in future 😄

**Comment by acognigni-evotecnia** [comment]
awesome. thanks
